#!/bin/sh

if [ $# -lt 1 ]; then
	echo "Usage: ${0##*/} FILE.txt [arguments to pandoc]"
	exit
fi

if [ ! -f "$1" ]; then
	echo "File '$1' does not exist."
	exit
fi

SOURCE=$1
NAME=`basename $1 .txt`
TMPDIR=/tmp/md2pf-$NAME

shift 1

mkdir -p $TMPDIR

pandoc -s -t context $@ -o $TMPDIR/$NAME.tex $SOURCE

(cd $TMPDIR; texexec $NAME.tex > /dev/null)

cp $TMPDIR/$NAME.pdf .
